### ISSUE TITLE
Double click on the "Continue" button on the Google social login registration page; we are getting "Unauthorized" error

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/tc-auth-lib#140] opened 2021-06-17 07:36 UTC
https://user-images.githubusercontent.com/42398485/122352236-8d5c8300-cf6c-11eb-8a28-55a3706d633f.mp4

1. Open the auth0 login page
2. Go to the Registration tab and click on the Google social Login
3. Authenticate the Google account
4. Enter the username and select the country
5. Double click on the Continue button

Double click on the "Continue" button on the Google social login registration page; we are getting an "Unauthorized" error

**Environment**:

 Edge 91.0.864.48 (Official build) (64-bit) | Windows 10

**Comment by lakshmiathreya** [comment] 2021-06-17 07:51
@codejamtc Pls mention the browser

**Comment by sachin-maheshwari** [comment] 2021-06-17 08:06
@lakshmiathreya she mentioned the browser "Edge 91.0.864.48 (Official build) (64-bit) | Windows 10". On Dev, my changes are working fine on chrome "Version 91.0.4472.77 (Official Build) (x86_64)".

**Comment by lakshmiathreya** [comment] 2021-06-17 08:11
@sachin-maheshwari we need to cover all major Browsers on Windows/Mac right?

**Comment by sachin-maheshwari** [comment] 2021-06-17 08:12
correct

**Comment by jmgasper** [comment] 2021-06-17 09:54
Challenge https://www.topcoder.com/challenges/53377ba0-5736-4371-a903-e48b434dba3d has been created for this ticket.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by jmgasper** [comment] 2021-06-17 09:54
Challenge https://www.topcoder.com/challenges/53377ba0-5736-4371-a903-e48b434dba3d has been assigned to obog.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by jmgasper** [comment] 2021-06-17 09:54
@atelomycterus - Can you look at this one when you're back from your traveling please?  Seems like we need a better handle on the disabling of that `Continue` button.

**Comment by SathyaJayabal** [comment] 2021-06-17 12:16
verified on dev @sachin-maheshwari 

https://user-images.githubusercontent.com/58783823/122394737-ee4b8180-cf93-11eb-919c-44f351583c31.mov

**Comment by sachin-maheshwari** [comment] 2021-06-17 13:18
@jmgasper let's disable "backward" browser flow too.

**Comment by jmgasper** [comment] 2021-06-17 19:46
Challenge https://www.topcoder.com/challenges/53377ba0-5736-4371-a903-e48b434dba3d obog has been unassigned.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by jmgasper** [comment] 2021-06-17 19:47
@atelomycterus - Moving this one to an F2F since it's high priority and I know you're unavailable for a few days.

**Comment by praveeno** [comment] 2021-06-18 01:36
how to run this project to debug

**Comment by jmgasper** [comment] 2021-06-18 01:40
@praveeno - Currently you can't easily.  You can test the current implementation at `https://topcoder-dev.com`

**Comment by jmgasper** [comment] 2021-06-18 21:12
@sachin-maheshwari - I deployed a fix, can you have a look please?  It's from the F2F, but I haven't closed it yet.

**Comment by sachin-maheshwari** [comment] 2021-06-19 03:14
@jmgasper "browser backward" direction flow is not stopped.  

@lakshmiathreya @coderhacker @codejamtc  @SathyaJayabal  QA can you please verify the changes on DEV.

**Comment by jmgasper** [comment] 2021-06-19 03:18
@sachin-maheshwari - Sorry, I missed that clarification above.  That'll have to be a separate ticket.  Can you log something with a video or more details please?

**Comment by sachin-maheshwari** [comment] 2021-06-19 03:28
@jmgasper NP. I think let's wait, I'll discuss with team and take this activity for all pages where it's needed.

**Comment by coderhacker** [comment] 2021-06-21 06:11
QA Comment: This is not fixed on DEV.  Its redirects to the same page after double click please see attached video.

https://user-images.githubusercontent.com/62358241/122714853-a1aec180-d285-11eb-81fa-fe5d15bc2931.mp4

**Comment by sachin-maheshwari** [comment] 2021-06-21 06:15
@jmgasper please just check above feedback by QA Team. Even it is not working even.

**Comment by jmgasper** [comment] 2021-06-21 07:14
@coderhacker - Could you provide a video from the beginning of the process please?  I just want to make sure I reproduce this correctly, thanks.

**Comment by coderhacker** [comment] 2021-06-21 08:53
@jmgasper: I am unable to reproduce this issue now, now passing this issue on dev. please find attached the video for the passed-on dev.

https://user-images.githubusercontent.com/62358241/122734906-23114e80-d29c-11eb-9e9e-40271026e874.mp4

**Comment by sachin-maheshwari** [comment] 2021-06-21 08:58
@coderhacker  Before going to deploy the code change on Prod, can you please reverify if this is still reproducible at Prod today ? CC @lakshmiathreya

**Comment by codejamtc** [comment] 2021-06-21 11:03
**Dev Environment:**

I checked the double click issue on dev and can't reproduce it on my end I think it is fixed https://github.com/topcoder-platform/tc-auth-lib/issues/140 🆗 

https://user-images.githubusercontent.com/42398485/122751757-c9198480-d2ad-11eb-9608-eae8981daeb0.mp4

But I can see two issues related to the double-clicking and browser back button

1. Try to register using an already registered Google account and after the validation, if the user clicks on the browser back button and then double click on the Continue button will still display the "Unauthorized" error (not sure this is covered from this particular fix)  ❌ 

https://user-images.githubusercontent.com/42398485/122752206-48a75380-d2ae-11eb-966d-04369399db89.mp4

2. If the user types an existing username (eg: 11111) and double click on the continue button will give a console error and you can continue after that by providing a valid username ❌ 

https://user-images.githubusercontent.com/42398485/122752238-4f35cb00-d2ae-11eb-807e-9594204c08f5.mp4

https://user-images.githubusercontent.com/42398485/122752244-5066f800-d2ae-11eb-8e5c-b62ce5f0bfab.mp4

**Production**:

- I checked the double click issue on prod and can't reproduce it on my end I think it is fixed 🆗 

https://user-images.githubusercontent.com/42398485/122751997-10a01080-d2ae-11eb-825b-4606c864b108.mp4

- Point 01 can be reproduced in Prod ❌

https://user-images.githubusercontent.com/42398485/122751997-10a01080-d2ae-11eb-825b-4606c864b108.mp4

- Point 02 is not reproducible in Prod 🆗 

https://user-images.githubusercontent.com/42398485/122751956-054ce500-d2ae-11eb-961e-0f0cf4750aad.mp4

@jmgasper @sachin-maheshwari @lakshmiathreya

**Comment by sachin-maheshwari** [comment] 2021-06-21 11:09
@lakshmiathreya @coderhacker that mean last deployed hotfix is sufficient on Prod. correct ?

**Comment by coderhacker** [comment] 2021-06-21 12:21
Based on the current finding marking this is an intermittent issue. please find the above evidence for more details.

**Comment by jmgasper** [comment] 2021-06-21 21:22
It sounds like there's something else at play here - a separate bug related to entering a username that's already taken, is that a correct summation?  Maybe we should get that reproducible and logged separately?

**Comment by codejamtc** [comment] 2021-06-22 04:38
> It sounds like there's something else at play here - a separate bug related to entering a username that's already taken, is that a correct summation? Maybe we should get that reproducible and logged separately?

@jmgasper https://github.com/topcoder-platform/tc-auth-lib/issues/144

**Comment by drasticdpk** [comment] 2021-06-24 07:12
Based on above discussion I am closing this ticket since it is intermittent Issue . We can open it for anything.  cc @lakshmiathreya

**Closed by drasticdpk** 2021-06-24 07:12 UTC
Labels: Dev Environment, P1, Production Enviroment, QA Pass in Dev, bug, intermittent issue

**Comment by codejamtc** [comment] 2021-07-08 08:35
https://user-images.githubusercontent.com/42398485/124890242-781bc700-dff5-11eb-8a48-0ceb4f6c87f9.mp4
