### ISSUE TITLE
Github login issue  

### ISSUE THREAD

**Issue by sachin-maheshwari** [topcoder-platform/tc-auth-lib#107] opened 2021-01-05 06:37 UTC
Issue reported on support team - 

Sharathkumar AnbuDec 27, 2020, 12:30 CST - I am not able to access either Topcoder community or Work Manager application.Reason - Something wrong with the logic of getting my handle from Auth0, due to which it's trying to get the member details for handle `sharathkumaranbu` instead of `Sharathkumar92`. `sharathkumaranbu` is actually my Github user name / email.Due to this I am not able to access any application which is running on V5. I believe one of the client also posted message saying they are not able to access Connect.It's a critical bug, please fix it immediately.
--
Sharathkumar Anbu
Jan 2, 2021, 20:59 GMT+5:30

Hi Tony, Sachin

I might have made miscommunicated to Tony on Slack. When I try to login with github, none of the web pages load. It just shows blank page. What I figured out from API calls was that, it's trying to fetch data for handle `sharathkumaranbu` which is my github user name and not my handle.

After i clear all data in local storage, cookies and when i login with username and password, it works asusual.

**Comment by lakshmiathreya** [comment] 2021-01-05 07:46
cc @sandhiyakavi @SathyaJayabal pls verify and close this ...

**Comment by SathyaJayabal** [comment] 2021-01-05 07:56
Verified with Sharath that the issue is fixed.

**Closed by SathyaJayabal** 2021-01-05 07:56 UTC

**Comment by sandhiyakavi** [comment] 2021-01-05 08:04
Verified from QA side.Able to login to WM, Connect and Community app without any issue.


https://user-images.githubusercontent.com/55895538/103620886-a30a5d00-4f77-11eb-8343-135e762cfae9.mp4


https://user-images.githubusercontent.com/55895538/103620899-aa316b00-4f77-11eb-96f3-c42b5824477f.mp4


https://user-images.githubusercontent.com/55895538/103620951-c2a18580-4f77-11eb-85d9-0610dbcc5437.mp4
